### PR TITLE
FIX (Regex) @W-17809567@ Fixed ENFILE/EMFILE errors for Regex engine

### LINKED ISSUE #1740: [BUG][code-analyzer] EMFILE: too many open files
### Have you tried to resolve this issue yourself first?

Yes

### Bug Description

When running code-analyzer, 

`sf code-analyzer run --severity-threshold 2 --output-file codescan/result-scan.csv -w ./common/**`

I receive the following message
`Error (1): EMFILE: too many open files, open 'C:\Users\douglas.midgley\AppData\Local\sf\node_modules\@salesforce\plugin-code-analyzer\node_modules\@salesforce\code-analyzer-regex-engine\package.json'`

### Output / Logs

[sfca-1738766366144.log](https://github.com/user-attachments/files/18674457/sfca-1738766366144.log)

### Steps To Reproduce

`sf code-analyzer run --severity-threshold 2 --output-file codescan/result-scan.csv -w ./common/**`

### Expected Behavior

code-analyzer runs without error

### Operating System

Windows 11

### Salesforce CLI Version

@salesforce/cli/2.73.9 win32-x64 node-v20.11.0

### Code Analyzer Plugin (code-analyzer) Version

@salesforce/sfdx-scanner 4.6.0 (4.6.0) code-analyzer 5.0.0-beta.0 (5.0.0-beta.0) dev 2.4.2 lightning-flow-scanner 2.34.0 (2.34.0)

### Node Version

v20.11.0

### Java Version

openjdk version "17.0.11" 2024-04-16 LTS OpenJDK Runtime Environment Zulu17.50+19-CA (build 17.0.11+9-LTS) OpenJDK 64-Bit Server VM Zulu17.50+19-CA (build 17.0.11+9-LTS, mixed mode, sharing)

### Python Version

_No response_

### Additional Context (Screenshots, Files, etc)

_No response_

### Workaround

_No response_

### Urgency

Low

### PR DESCRIPTION
**Pull request by jfeingold35**
This PR resolves https://github.com/forcedotcom/sfdx-scanner/issues/1740.
The root cause is that the `regex` engine was attempting to process every single file in the workspace in parallel via `async/await` and `Promise.all` instead of doing it serially. In a truly massive workspace (like, >20k files), it's possible to hit the system-level limit on how many files are allowed to be open at once.
The fix is that the engine has been modified to process files in batches of 1000, allowing for a more controlled level of parallelism.
I couldn't think of a way to add an automated test for this, short of adding 20,000 new files to repo, so I chose not to.

### CODE REVIEW

File: packages/code-analyzer-regex-engine/src/engine.ts [hunk 1]
```diff
@@ -93,9 +93,20 @@ export class RegexEngine extends Engine {
 
     async runRules(ruleNames: string[], runOptions: RunOptions): Promise<EngineRunResults> {
         const textFiles: string[] = await this.getTextFiles(runOptions.workspace);
-        const ruleRunPromises: Promise<Violation[]>[] = textFiles.map(file => this.runRulesForFile(file, ruleNames));
+        let batchMultiplier = 0;
+        let violations: Violation[] = [];
+        while (batchMultiplier * 1000 < textFiles.length) {
```
Comment (jag-j) [inline packages/code-analyzer-regex-engine/src/engine.ts]: Nit - Can you extract 1000 to BATCH_SIZE constant ?

File: packages/code-analyzer-regex-engine/src/engine.ts [hunk 2]
```diff
@@ -93,9 +93,20 @@ export class RegexEngine extends Engine {
...
+            // Turns out there's a system-level limit on how many files can be open at once. In order to avoid hitting
+            // this limit while still reaping the benefits of `Promise.all()`, we'll process the files in batches of
+            // 1000.
+            const textFileBatch = textFiles.slice(batchMultiplier * 1000, (batchMultiplier + 1) * 1000);
+            const ruleRunPromises: Promise<Violation[]>[] = textFileBatch.map(file => this.runRulesForFile(file, ruleNames));
+            const newViolations = (await Promise.all(ruleRunPromises)).flat();
+            violations = [...violations, ...newViolations];
```
Comment (jag-j) [inline packages/code-analyzer-regex-engine/src/engine.ts]: Can we use push here instead ?

**Review by jag-j — APPROVED** [review]
